---
- name: Install packages (python-setuptools, python-pip, python-devel, git)
  yum: pkg={{item}} state=installed
  with_items:
    - python-setuptools
    - python-pip
    - python-devel
    - git

- name: Install cython
  command: /usr/bin/pip install cython creates=/usr/lib64/python2.6/site-packages/cython.py

- name: Check if the /tmp/pyslurm
  stat: path=/tmp/pyslurm
  register: pyslurm_dir

- name: Install pyslurm (via git)
  git: repo=git://github.com/gingergeeks/pyslurm dest=/tmp/pyslurm
  when: not pyslurm_dir.stat.exists

- name: Build pyslurm
  command: chdir=/tmp/pyslurm /usr/bin/python setup.py build --slurm=/usr/local/slurm creates=/tmp/pyslurm/build

- name: Build pyslurm
  command: chdir=/tmp/pyslurm /usr/bin/python setup.py install creates=/usr/lib64/python2.6/site-packages/pyslurm
