---
- name: torque-server torque-scheduler torque-client
  yum: pkg={{item}} state=installed
  with_items:
    - torque-server
    - torque-scheduler
    - torque-client
    - munge

- name: set server_name
  shell: echo $HOSTNAME > /var/lib/torque/server_name

- name: create munge key
  shell: /usr/sbin/create-munge-key -f

- name: config pbs_server
  template: src=nodes dest=/var/lib/torque/server_priv/

- name: Start pbs_server
  service: name=pbs_server state=restarted enabled=yes

- name: Start munge
  service: name=munge state=restarted enabled=yes

- name: Install pbs_server init script
  copy: src=init_queue.sh dest=/tmp/init_queue.sh mode=0755

- name: run init queue script
  shell: /tmp/init_queue.sh

- name: Start pbs_sched
  service: name=pbs_sched state=restarted enabled=yes
