---
- hosts: all
  remote_user: vagrant
  sudo: yes
  tasks:
  - name: install nfs packages
    yum: pkg={{item}} state=installed
    with_items:
      - nfs-utils
      - portmap
  - name: copy exports file
    copy: src=./files/exports dest=/etc/exports mode=0644
  - name: get_url openmpi packages
    get_url: url=http://linuxsoft.cern.ch/cern/slc61/x86_64/yum/updates/openmpi-1.5.4-1.el6.x86_64.rpm dest=/tmp/openmpi-1.5.4-1.el6.x86_64.rpm
  - name: install openmpi packages
    raw: yum -y localinstall /tmp/openmpi-1.5.4-1.el6.x86_64.rpm
  - name: get_url openmpi-devel packages
    get_url: url=http://linuxsoft.cern.ch/cern/slc61/x86_64/yum/updates/openmpi-devel-1.5.4-1.el6.x86_64.rpm dest=/tmp/openmpi-devel-1.5.4-1.el6.x86_64.rpm
  - name: install openmpi-devel packages
    raw: yum -y localinstall /tmp/openmpi-devel-1.5.4-1.el6.x86_64.rpm
  - name: mkdir .ssh
    file: dest=/root/.ssh owner=root group=root state=directory
  - name: make cluster, private key copy
    copy: src=./files/id_rsa dest=/root/.ssh/id_rsa mode=0600
  - name: make cluster, public key copy
    copy: src=./files/id_rsa.pub dest=/root/.ssh/id_rsa.pub mode=0600
  - name: make cluster, authorized_keys
    copy: src=./files/authorized_keys dest=/root/.ssh/authorized_keys mode=0600
  - name: make cluster, known_hosts
    copy: src=./files/known_hosts dest=/root/.ssh/known_hosts mode=0644
  - name: ensure rpcbind service
    service: name=rpcbind state=restarted enabled=yes
  - name: ensure nfs service
    service: name=nfs state=restarted enabled=yes
  - name: add module load openmpi to .bashrc
    lineinfile: dest=/root/.bashrc state=present insertafter=EOF line="module load openmpi-x86_64"

  vars:
    node_name: "worker1"
    cpu_num: 2

  roles:
  - torque-server
