---
- hosts: all
  remote_user: vagrant
  sudo: yes
  tasks:
  - name: install nfs packages
    yum: pkg=nfs-utils state=installed
  - name: mkdir .ssh
    file: dest=/root/.ssh owner=root group=root state=directory
  - name: make cluster, private key copy
    copy: src=./files/id_rsa dest=/root/.ssh/id_rsa mode=0600
  - name: make cluster, public key copy
    copy: src=./files/id_rsa.pub dest=/root/.ssh/id_rsa.pub mode=0600
  - name: make cluster, authorized_keys
    copy: src=./files/authorized_keys dest=/root/.ssh/authorized_keys mode=0600
  - name: make cluster, known_hosts
    shell: /usr/bin/ssh-keyscan controller >> /root/.ssh/known_hosts
  - name: get_url openmpi packages
    get_url: url=http://linuxsoft.cern.ch/cern/slc61/x86_64/yum/updates/openmpi-1.5.4-1.el6.x86_64.rpm dest=/tmp/openmpi-1.5.4-1.el6.x86_64.rpm
  - name: install openmpi packages
    raw: yum -y localinstall /tmp/openmpi-1.5.4-1.el6.x86_64.rpm
  - name: mount NFS /EDISON
    lineinfile: dest=/etc/fstab state=present insertafter=EOF line="controller:/EDISON          /EDISON                 nfs     defaults        0        0" 
  - name: mount /EDISON
    shell: /bin/mount -a
  - name: add module load openmpi to .bashrc
    lineinfile: dest=/root/.bashrc state=present insertafter=EOF line="module load openmpi-x86_64"

  vars:
    pbs_server: "controller"

  roles:
  - torque-mom
